#!/bin/bash

#submits bcbio project to the queue with n threads
#adjust ppn and walltime depending on the project
#experience is that the best combination for WES and SK HPC is 7cores/50G

#PBS -l walltime=240:00:00,nodes=1:ppn=7
#PBS -joe .
#PBS -d .
#PBS -l vmem=50g,mem=50g

echo "START: " `date`;

module load java/1.8.0_91

if [ -z $threads ]
then
    threads=7
fi
echo $project $threads

bcbio_nextgen.py ../config/${project}.yaml -n $threads

echo "END: " `date`;


