#!/bin/bash
#PBS -l walltime=1:00:00,nodes=1:ppn=20
#PBS -joe .
#PBS -d .
#PBS -l vmem=50g

mkdir newreference;
ref=/home/naumenko/work/reference;

STAR --genomeDir $ref --readFilesIn $left $right --runThreadN 20;

STAR --runMode genomeGenerate --genomeDir newreference \
  --genomeFastaFiles $ref/GRCm38.p4.genome.fa \
  --sjdbGTFfile $ref/gencode.vM8.annotation.gtf --runThreadN 20 \
  --sjdbOverhang 99 \
  --sjdbFileChrStartEnd SJ.out.tab;

rm Aligned.out.sam;

STAR --genomeDir newreference --readFilesIn $left $right --runThread 20;

rm newreference/*;
rmdir newreference;
