#!/usr/bin/perl

#wrapper script for pbsnodes
#naumenko.sa 28.03.2012

use strict;

open(IN,"pbsnodes|");
print "NODENAME\tCORES\tLOAD\tSTATE\n";
print "---------------------------------------------------------------------------------------------\n";
while(<IN>)
{
    chomp;
    if ($_ =~ /^r/)
    {
	my $node = $_;
	my $state = <IN>;
	my $powerstate = <IN>;
	chomp $state;
	$state =~ s/state//;
	$state =~ s/=//;
	my $np = <IN>;
	chomp $np;
	$np =~ s/np//;
	$np =~ s/=//;
	my $ntype = <IN>;
	
	my $status = <IN>;
	$status =~ s/^\s+//;
	
	    #awk -F '=' '{print $2}' | awk -F '/' '{print "-("$1")+1"}' | bc 
	    
	    
	my $cpu_busy=0;
	if ($status =~ /^jobs/)
	{
	    my @ar3 = split("=",$status);
	    
	    my $s = $ar3[1];
	    $s =~ s/\/[0-9]+//g;
	    my @ar4 = split(",",$s);
	    foreach my $t(@ar4)
	    {
		if ($t =~ /-/)
		{
		    my @ar5=split("-",$t);
		    $cpu_busy += $ar5[1]-$ar5[0]+1;
		}
		else
		{
		    $cpu_busy +=1;
		}
	    }
	    #$cpu_busy=`echo $status | awk -F '=' '{print $2}' | awk -F '/' '{print "-("$1")+1"} | bc`;
	    
	    $status = <IN>;
	}
	my $mom1 = <IN>;
	my $mom2 = <IN>;
	my $cores=0;
	my @params = split(",",$status);
	my %prms;
	foreach my $par (@params)
	{
	    my @ar = split("=", $par);
	    $prms{$ar[0]}=$ar[1];
	}
	my $gpus = <IN>;
	#print $status."\n";
	print $node."\t".$np."(".$cpu_busy.")"."\t".$prms{"loadave"}."\t".$state."\n";
	
    }
}
close(IN);