#!/bin/bash

#PBS -d .
#PBS -l walltime=10:00:00,nodes=1:ppn=30,mem=10G,vmem=10G
#PBS -joe .

# run with -o and without -o to get bootstrap support for all branches
# with outgroup to check bootstrap

# avx should be faster than sse

date
hostname
raxml=/hpf/largeprojects/ccmbio/naumenko/tools/standard-RAxML/raxmlHPC-PTHREADS-AVX

ogroup=""
if [ -n "$outgroup" ]
then
    ogroup="-o "$outgroup
fi

$raxml -T 30 -f a -s $align -n $align.tree -m GTRGAMMAI $ogroup -x 12345 -p 12345 -# 1000

# -m GTRCAT -V

# -m GTRGAMMAI 

date

#--HKY85
